steps:
  - name: gcr.io/cloud-builders/git
    #args: ['fetch', '--unshallow']
    args: ['--version']
  - name: 'ubuntu'
    args: ['echo', 'hello ${_SUB_VALUE} $PROJECT_ID']
substitutions:
    _SUB_VALUE: world
options:
    substitution_option: 'ALLOW_LOOSE'
    